spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/interviewPrep
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

  profiles:
    include: oauth

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
